version: '3.9'

services:
  # NATS Service
  nats-server:
    image: nats:2.10.14

  # Client Api Gateway
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVER_URL}

  # Auth Microservice
  auth-ms:
    build:
      context: ./auth-microservice
      dockerfile: Dockerfile.prod
    image: auth-microservice-prod
    volumes: 
      - ./auth-microservice/src:/usr/src/app/src
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVER_URL}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  # Products Microsercice
  products-ms:
    build:
      context: ./products-microservice
      dockerfile: Dockerfile.prod
    image: products-microservice-prod
    environment:
      - PORT=3001
      - DATABASE_URL=file:./dev.db
      - NATS_SERVERS=${NATS_SERVER_URL}

  # Orders Microsercice
  orders-ms:
    build:
      context: ./orders-microservice
      dockerfile: Dockerfile.prod
      args:
        - ORDERS_DB_CONNECT_URL=${ORDERS_DB_CONNECT_URL}
    image: orders-microservice-prod
    environment:
      - PORT=3000
      - DATABASE_URL=${ORDERS_DB_CONNECT_URL}
      - NATS_SERVERS=${NATS_SERVER_URL}

  # # Orders Postgres Database
  # orders-db:
  #   container_name: orders_database
  #   image: postgres:16.2
  #   restart: always
  #   volumes:
  #     - ./orders-microservice/postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=${ORDERS_DB_POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${ORDERS_DB_POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${ORDERS_DB_POSTGRES_DB}

  # Payments Microservice
  payments-ms:
    build:
      context: ./payments-microservice
      dockerfile: Dockerfile.prod
    image: payments-microservice-prod
    ports: 
      - ${PAYMENT_MS_PORT}:${PAYMENT_MS_PORT}
    environment:
      - PORT=${PAYMENT_MS_PORT}
      - NATS_SERVERS=${NATS_SERVER_URL}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}